version: "3.5"
services:
   frontend:
     build: ./frontend
     container_name: "frontend"
     volumes:
       - ../frontend:/frontend     
     ports:
       - "4200:4200"
     command: ng serve --host 0.0.0.0 --port 4200 --poll=2000
   backend:
     build: ./backend
     container_name: "backend"
     ports:
       - "5000:5000"
     command: flask run --host=0.0.0.0
